// Writes the two source files the app builds from but does not commit, and skips
// each one while its inputs are unchanged:
// - src/ui/icons.generated.ts: the Mac app's icons (src/ui/Icons.tsx) as SVG markup, so
//   both apps draw the same icons.
// - src/ui/vertexShader.generated.ts: the vertex shader the backdrop's fragment shaders
//   read from, which @paper-design/shaders does not export.
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const app = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const desktop = resolve(app, '../../src');
const cache = resolve(app, 'node_modules/.cache');
const iconsOut = resolve(app, 'src/ui/icons.generated.ts');
const iconsStamp = resolve(cache, 'sikemux-icons.json');
const shaderOut = resolve(app, 'src/ui/vertexShader.generated.ts');
const shaderSource = resolve(app, 'node_modules/@paper-design/shaders/dist/vertex-shader.js');

const mtime = (path) => (existsSync(path) ? statSync(path).mtimeMs : null);
const LOGO_FILES = { IconCodex: 'codex.svg', IconOmp: 'omp.svg' };

function iconsUpToDate() {
  if (!existsSync(iconsOut) || !existsSync(iconsStamp)) return false;
  const inputs = JSON.parse(readFileSync(iconsStamp, 'utf8'));
  return Object.entries(inputs).every(([path, time]) => mtime(path) === time);
}

async function generateIcons() {
  const bundle = resolve(cache, 'sikemux-icons.mjs');
  const entry = `
import { renderToStaticMarkup } from "react-dom/server";
import * as Icons from ${JSON.stringify(resolve(desktop, 'ui/Icons.tsx'))};
export const rendered = Object.fromEntries(
  Object.entries(Icons)
    .filter(([name, Icon]) => typeof Icon === "function" && (name.startsWith("Icon") || name === "Logo"))
    .map(([name, Icon]) => [name, renderToStaticMarkup(Icon({ size: 16, percent: 80 }))]),
);
`;
  mkdirSync(cache, { recursive: true });
  const { metafile } = await build({
    stdin: { contents: entry, resolveDir: app, loader: 'tsx' },
    bundle: true,
    platform: 'node',
    format: 'esm',
    jsx: 'automatic',
    loader: { '.svg': 'dataurl' },
    packages: 'external',
    outfile: bundle,
    logLevel: 'warning',
    metafile: true,
    absWorkingDir: app,
  });
  const { rendered } = await import(`${pathToFileURL(bundle).href}?${Date.now()}`);
  rmSync(bundle);

  const logos = Object.entries(LOGO_FILES).map(([name, file]) => [name, resolve(desktop, 'assets/agent-logos', file)]);
  for (const [name, path] of logos) rendered[name] = readFileSync(path, 'utf8');

  const markup = Object.fromEntries(
    Object.entries(rendered)
      .filter(([, svg]) => svg.startsWith('<svg'))
      .map(([name, svg]) => [name, svg.replace(/ aria-hidden="true"/g, '')]),
  );
  writeFileSync(
    iconsOut,
    `// Generated by scripts/generate.mjs from src/ui/Icons.tsx. Do not edit.\n` +
      `export const ICONS = ${JSON.stringify(markup, null, 2)} as const;\n` +
      `export type IconName = keyof typeof ICONS;\n`,
  );

  const inputs = [
    ...Object.keys(metafile.inputs)
      .filter((path) => !path.startsWith('<stdin>'))
      .map((path) => resolve(app, path)),
    ...logos.map(([, path]) => path),
    fileURLToPath(import.meta.url),
  ];
  writeFileSync(iconsStamp, JSON.stringify(Object.fromEntries(inputs.map((path) => [path, mtime(path)]))));
  console.log(`icons: ${Object.keys(markup).length} from the Mac app`);
}

async function generateShader() {
  const generatedAt = mtime(shaderOut);
  if (generatedAt !== null && generatedAt >= mtime(shaderSource)) return;
  const { vertexShaderSource } = await import(pathToFileURL(shaderSource).href);
  writeFileSync(
    shaderOut,
    `// Generated by scripts/generate.mjs from @paper-design/shaders.\nexport const vertexShaderSource = ${JSON.stringify(vertexShaderSource)};\n`,
  );
}

export async function generate() {
  await generateShader();
  if (iconsUpToDate()) return;
  try {
    await generateIcons();
  } catch (error) {
    if (!existsSync(iconsOut)) throw error;
    console.warn(`icons: kept the last ones; the Mac app's icons did not build:\n${error.message}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await generate();
