// Generated by scripts/generate-agent-tools.mjs from browser/tools.json. Do not edit by hand.
pub const BROWSER_METHODS: &[&str] = &[
    "browser.navigate",
    "browser.state",
    "browser.click",
    "browser.type",
    "browser.press",
    "browser.drag",
    "browser.upload",
    "browser.dialog",
    "browser.scroll",
    "browser.extract",
    "browser.evaluate",
    "browser.network",
    "browser.console",
    "browser.screenshot",
    "browser.annotate",
    "browser.record",
    "browser.wait",
    "browser.back",
    "browser.forward",
    "browser.tabs",
    "browser.tab.switch",
    "browser.tab.close",
];

pub const HARNESS_METHODS: &[&str] = &[
    "workspace.inspect",
    "task.start",
    "task.read",
    "task.stop",
    "ui.open",
    "events.wait",
];
